server:
  port: 0

spring:
  application:
    name: product-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jpashop?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: sa
#    password: km971gb5!!
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.productservice: DEBUG

